module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: # Define your favicon file path, e.g., /img/favicon.ico

    footer:
        since: # Add the year when your site started
        customText: # Add any custom text for the footer

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: # Add emoji set if needed (e.g., GitHub, Twitter, etc.)
        subtitle: # Optional subtitle for sidebar
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus # Enable a comment provider if needed (e.g., disqus, utterances, etc.)

        # Disqus configuration
        disqusjs:
            shortname: # Add your Disqus shortname
            apiUrl: # Optional API URL for Disqus
            apiKey: # Add API key if required
            admin:
            adminLabel:

        # Utterances configuration
        utterances:
            repo: # Add your GitHub repo for comments
            issueTerm: pathname
            label:

        # Beaudar configuration
        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme: # Define your preferred theme (e.g., light, dark)

        # Remark42 configuration
        remark42:
            host: # Define Remark42 host URL
            site: # Add your site domain
            locale:

        # Vssue configuration
        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration
        waline:
            serverURL: # Add Waline server URL
            lang:
            visitor: true
            avatar: true
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder: Add your comment...

        # Twikoo configuration
        twikoo:
            envId: # Add Twikoo environment ID
            region: # Define Twikoo region (e.g., cn, us)
            path:
            lang:

        # Giscus configuration
        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme: # Define light theme (optional)
            darkTheme: # Define dark theme (optional)
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        # Gitalk configuration
        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        # Cusdis configuration
        cusdis:
            host:
            id:

    widgets:
        homepage: [] # Add widget components for homepage
        page: [] # Add widget components for inner pages

    opengraph:
        twitter:
            site: # Your Twitter username (e.g., @yourhandle)
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: # Define a default image URL for OpenGraph

    colorScheme:
        toggle: true # Display a light/dark mode toggle
        default: auto # Set default mode (auto, light, dark)

    imageProcessing:
        cover:
            enabled: true # Enable cover image processing
        content:
            enabled: true # Enable content image processing
